
export type HsnSacCode = {
  code: string;
  description: string;
};

export const hsnSacCodes: HsnSacCode[] = [
  { code: '0101', description: 'LIVE HORSES, ASSES, MULES AND HINNIES' },
  { code: '0102', description: 'LIVE BOVINE ANIMALS' },
  { code: '0103', description: 'LIVE SWINE' },
  { code: '0104', description: 'LIVE SHEEP AND GOATS' },
  { code: '0105', description: 'LIVE POULTRY, THAT IS TO SAY, FOWLS OF THE SPECIES GALLUS DOMESTICUS, DUCKS, GEESE, TURKEYS AND GUINEA FOWLS' },
  { code: '0106', description: 'OTHER LIVE ANIMALS' },
  { code: '0201', description: 'MEAT OF BOVINE ANIMALS, FRESH AND CHILLED' },
  { code: '0202', description: 'MEAT OF BOVINE ANIMALS, FROZEN' },
  { code: '0203', description: 'MEAT OF SWINE, FRESH, CHILLED OR FROZEN' },
  { code: '0204', description: 'MEAT OF SHEEP OR GOATS, FRESH, CHILLED OR FROZEN' },
  { code: '0206', description: 'EDIBLE OFFAL OF BOVINE ANIMALS, SWINE, SHEEP, GOATS, HORSES, ASSES, MULES OR HINNIES, FRESH, CHILLED OR FROZEN' },
  { code: '0207', description: 'MEAT AND EDIBLE OFFAL, OF THE POULTRY OF HEADING 0105, FRESH, CHILLED OR FROZEN' },
  { code: '0208', description: 'OTHER MEAT AND EDIBLE MEAT OFFAL, FRESH, CHILLED OR FROZEN' },
  { code: '0209', description: 'PIG FAT, FREE OF LEAN MEAT, AND POULTRY FAT, NOT RENDERED OR OTHERWISE EXTRACTED, FRESH, CHILLED, FROZEN, SALTED, IN BRINE, DRIED OR SMOKED' },
  { code: '0210', description: 'MEAT AND EDIBLE MEAT OFFAL, SALTED, IN BRINE, DRIED OR SMOKED; EDIBLE FLOURS AND MEALS OF MEAT OR MEAT OFFAL' },
  { code: '0301', description: 'LIVE FISH' },
  { code: '0302', description: 'FISH, FRESH OR CHILLED, EXCLUDING FISH FILLETS AND OTHER FISH MEAT OF HEADING 0304' },
  { code: '0303', description: 'FISH, FROZEN, EXCLUDING FISH FILLETS AND OTHER FISH MEAT OF HEADING 0304' },
  { code: '0304', description: 'FISH FILLETS AND OTHER FISH MEAT (WHETHER OR NOT MINCED), FRESH, CHILLED OR FROZEN' },
  { code: '0305', description: 'FISH, DRIED, SALTED OR IN BRINE; SMOKED FISH, WHETHER OR NOT COOKED BEFORE OR DURING THE SMOKING PROCESS; FLOURS, MEALS AND PELLETS OF FISH, FIT FOR HUMAN CONSUMPTION' },
  { code: '0306', description: 'CRUSTACEANS, WHETHER IN SHELL OR NOT, LIVE, FRESH, CHILLED, FROZEN, DRIED, SALTED OR IN BRINE; CRUSTACEANS, IN SHELL, COOKED BY STEAMING OR BY BOILING IN WATER, WHETHER OR NOT CHILLED, FROZEN, DRIED, SALTED OR IN BRINE; FLOURS, MEALS AND PELLETS OF CRUSTACEANS, FIT FOR HUMAN CONSUMPTION' },
  { code: '0307', description: 'MOLLUSCS, WHETHER IN SHELL OR NOT, LIVE, FRESH, CHILLED, FROZEN, DRIED, SALTED OR IN BRINE; AQUATIC INVERTEBRATES OTHER THAN CRUSTACEANS AND MOLLUSCS, LIVE, FRESH, CHILLED, FROZEN, DRIED, SALTED OR IN BRINE; FLOURS, MEALS AND PELLETS OF AQUATIC INVERTEBRATES OTHER THAN CRUSTACEANS, FIT FOR HUMAN CONSUMPTION' },
  { code: '0308', description: 'AQUATIC INVERTEBRATES OTHER THAN CRUSTACEANS AND MOLLUSCS, LIVE, FRESH, CHILLED, FROZEN, DRIED, SALTED OR IN BRINE; SMOKED AQUATIC INVERTEBRATES OTHER THAN CRUSTACEANS AND MOLLUSCS, WHETHER OR NOT COOKED BEFORE OR DURING THE SMOKING PROCESS; FLOURS, MEALS AND PELLETS OF AQUATIC INVERTEBRATES OTHER THAN CRUSTACEANS AND MOLLUSCS, FIT FOR HUMAN CONSUMPTION' },
  { code: '0401', description: 'MILK AND CREAM, NOT CONCENTRATED NOR CONTAINING ADDED SUGAR OR OTHER SWEETENING MATTER' },
  { code: '0402', description: 'MILK AND CREAM, CONCENTRATED OR CONTAINING ADDED SUGAR OR OTHER SWEETENING MATTER' },
  { code: '0403', description: 'BUTTERMILK, CURDLED MILK AND CREAM, YOGURT, KEPHIR AND OTHER FERMENTED OR ACIDIFIED MILK AND CREAM, WHETHER OR NOT CONCENTRATED OR CONTAINING ADDED SUGAR OR OTHER SWEETENING MATTER OR FLAVOURED OR CONTAINING ADDED FRUIT, NUTS OR COCOA' },
  { code: '0404', description: 'WHEY, WHETHER OR NOT CONCENTRATED OR CONTAINING ADDED SUGAR OR OTHER SWEETENING MATTER; PRODUCTS CONSISTING OF NATURAL MILK CONSTITUENTS, WHETHER OR NOT CONTAINING ADDED SUGAR OR OTHER SWEETENING MATTER, NOT ELSEWHERE SPECIFIED OR INCLUDED' },
  { code: '0405', description: 'BUTTER AND OTHER FATS AND OILS DERIVED FROM MILK; DAIRY SPREADS' },
  { code: '0406', description: 'CHEESE AND CURD' },
  { code: '0407', description: 'BIRDS\' EGGS, IN SHELL, FRESH, PRESERVED OR COOKED' },
  { code: '0408', description: 'BIRDS\' EGGS, NOT IN SHELL, AND EGG YOLKS, FRESH, DRIED, COOKED BY STEAMING OR BY BOILING IN WATER, MOULDED, FROZEN OR OTHERWISE PRESERVED, WHETHER OR NOT CONTAINING ADDED SUGAR OR OTHER SWEETENING MATTER' },
  { code: '0409', description: 'NATURAL HONEY' },
  { code: '0410', description: 'EDIBLE PRODUCTS OF ANIMAL ORIGIN, NOT ELSEWHERE SPECIFIED OR INCLUDED' },
  { code: '995411', description: 'General construction services of single or multi dwelling residential buildings' },
  { code: '995412', description: 'General construction services of other residential buildings' },
  { code: '995413', description: 'General construction services of industrial buildings' },
  { code: '995414', description: 'General construction services of commercial buildings' },
  { code: '995415', description: 'General construction services of other non-residential buildings' },
  { code: '995416', description: 'General construction services of other civil engineering works' },
  { code: '995419', description: 'Services involving repair, alterations, additions, replacements, renovation, maintenance or remodelling of the buildings covered above.' },
  { code: '995421', description: 'Demolition services' },
  { code: '995422', description: 'Site formation and clearance services including preparation services to make sites ready for subsequent construction work, test drilling & boring & core extraction, digging of trenches.' },
  { code: '995423', description: 'Excavating and earthmoving services' },
  { code: '995424', description: 'Water well drilling and septic system installation services' },
  { code: '995425', description: 'Other site preparation services n.e.c' },
  { code: '995426', description: 'Painting services' },
  { code: '995427', description: 'Other finishing services' },
  { code: '995428', description: 'Assembly and erection of prefabricated constructions' },
  { code: '995429', description: 'Other services of assembly and erection of prefabricated constructions' },
  { code: "998311", description: "Management consulting and management services including financial, strategic, human resources, marketing, operations and supply chain management." },
  { code: "998312", description: "Business consulting services including public relations services" },
  { code: "998313", description: "Information technology (IT) consulting and support services" },
  { code: "998314", description: "Information technology (IT) design and development services" },
  { code: "998315", description: "Hosting and information technology (IT) infrastructure provisioning services" },
  { code: "998316", description: "IT infrastructure and network management services" },
  { code: "998319", description: "Other information technology services n.e.c." },
  { code: "998591", description: "Subscription services" },
  { code: "998592", description: "Customs clearance services" },
  { code: "998593", description: "Ship broking services" },
  { code: "998594", description: "Travel arrangement and reservation services" },
  { code: "998595", description: "Tour operator services" },
  { code: "998596", description: "Services of tourist guides" },
  { code: "998597", description: "Services of tourism promotion and visitor information" },
  { code: "998598", description: "Other travel arrangement and related services n.e.c." },
  { code: "998599", description: "Other support services n.e.c." }
];
